#!/bin/bash
# Copyright © BonvScripts
function ip_address(){
  local IP="$( ip addr | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -Ev "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1 )"
  [ -z "${IP}" ] && IP="$(curl -4s ipv4.icanhazip.com)"
  [ -z "${IP}" ] && IP="$(curl -4s ipinfo.io/ip)"
  [ ! -z "${IP}" ] && echo "${IP}" || echo '0.0.0.0'
}
clear
echo -e "\n\e[38;5;208m ★ \e[1;38;5;231mMantoSSH\e[38;5;208m ★ \e[0m\n"
echo -e "\e[1;97m Create Account\e[0m"
echo -e ""
readP0() { read -p "$(printf "%b" "\e[32m  Username: \e[0m")" User; }
readP0
while [[ "$(cat < /etc/passwd | cut -d: -f1 | grep -x -c -E "^${User}")" -ge 1 ]]; do
 echo -e "\e[1;31m Username already exists on your server, please try another username\e[0m"
 readP0
done
read -p "$(printf "%b" "\e[32m  Password: \e[0m")" Pass
readP1() { read -p "$(printf "%b" "\e[32m  Active Days: \e[0m")" Days; }
readP1
until [[ "$Days" =~ ^[1-9][0-9]*$ ]]; do
 echo -e "\e[1;31m Invalid expiry day count\e[0m"
 readP1
done
echo -e ""
clear
Today="$(date +%s)"
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%B %d, %Y')
AcclistFilename="$(date "+/tmp/%Y-%m-%d-%H%M%S-account.txt")"
touch ${AcclistFilename}
#####
useradd -o -u 1003 -p $(openssl passwd -1 "${Pass}") -c "MantoSSH" -m -s /bin/false -e $Expiration ${User} &> /dev/null
clear
echo -e ""
echo -e "\n\e[38;5;208m ★ \e[1;38;5;231mMantoSSH\e[38;5;208m ★ \e[0m\n"
echo -e " Your Account:" | tee -a ${AcclistFilename}
echo -e "\e[32m  Username:\e[0m $User" | tee -a ${AcclistFilename}
echo -e "\e[32m  Password:\e[0m $Pass" | tee -a ${AcclistFilename}
echo -e "\e[32m  Account Expiry:\e[0m $Expiration_Display" | tee -a ${AcclistFilename}
echo -e "\e[32m  Host/IP:\e[0m $(ip_address)" | tee -a ${AcclistFilename}
echo -e "\e[32m Account logfile:\e[0m $AcclistFilename"
echo -e "" | tee -a ${AcclistFilename}
sed -i "s|[\\]e\[[0-9;]*[a-zA-Z]||g" ${AcclistFilename}
sed -i "s|\x1B\[[0-9;]*[a-zA-Z]||g" ${AcclistFilename}
echo -e ""
